const puns = [
	'Have an egg-cellent day!',
	'Lettuce us celebrate!',
	'Thyme is money.',
	'You butter believe it.',
	'Nice to meat you.',
	'Becoming a vegetarian is a huge missed steak.',
	'Doughnut take us lightly.',
	'The path of yeast resistance.',
	'Another one beats the crust.',
	'Pickle for your thoughts.',
	'A salt with a deadly weapon.',
	'Batter up!',
	'Robert Brownie Jr.',
	'Good morning Viet-nom!',
	"Let's give 'em something to taco 'bout!",
	"It's nacho your problem.",
	"I'm a weirddough.",
	'What the hell am I doughing here?',
	"Let's cut to the cheese.",
	'I doughnot belong here.',
	'I hope you find inner peas.',
	'This may sound bananas but I find you a-peeling.',
	'Chill today, hot tamale.',
	'Making ends meat.',
	'Salami-get this straight.',
	'Iceberg! Straight ahead.',
	'Lime yours.',
	'Pasta la vista, baby!',
	'Penne for your thoughts.',
	"It feels like you don't carrot all.",
	'Berried alive.',
	'Hope to see you again so we can ketchup.',
	'Well, well, well. Would you look at the thyme?',
	'You butter back off, pal.',
	"I'm kind of a big dill.",
	"Don't go bacon my heart.",
	'Lettuce turnip the beet!',
	'I get a little chilli.',
	'Blurred limes.',
	'Wu-Tang Flan.',
	"Don't leek my secrets.",
	"You're so absinth-minded!",
	'I love Melon DeGeneres!',
	"There's Polenta go around!",
	"You're my butter half!",
	'I love you very mochi.',
	'We make a beautiful pear.',
	"The s'more I know you, the s'more I love you.",
	'Thanks for pudding up with me.',
	"Here's my number, so Kale me maybe?",
	'Bean there, done that.',
	"You're a has bean.",
	'John Lemon.',
	"You're a real pizzawork.",
	'You look radishing today.',
	"Y'all bready for this?",
	'I donut understand food puns.',
	'I only have fries for you.',
	"You're acting unbeerable.",
	'Jello from the other side!',
	"If you were a fruit, you'd be a fine apple.",
	'The Carbdashians.',
	'Just beet it.',
	'Turnip for what?',
	'Olive you.',
	"I don't believe you. You're an impasta!",
	'I value our friend-chip.',
	'I have so mushroom in my heart.',
	"Donut you know you're special?",
	"You've stolen a pizza my heart.",
	'Soda think you can help me out?',
	'Pretty peas?',
	'Orange you so excited?',
	'Thanks a latte.',
	'Kiwi be friends?',
	'I love you from my head tomatoes.',
	"That's what cheese said.",
	"I'm a real funghi!",
	"I'm muffin without you.",
	'Water you doing?',
	'Gurl, peas.',
	'I am berry excited!',
	'Gouda luck!',
	"It's fry-day!",
	'Thank you very matcha.',
	"I'm so mad ice cream!",
	"I'm your biggest flan.",
	'Donut ever leave.',
	"I'm the wurst.",
	"Don't settle for mediokra!",
	"You're the apple of my ribeye.",
	'I tiramisu already!',
	'Udon know me!',
	'Control your tempura please!',
	'Feeling a little melon-choly.',
	'My heart beets for you.',
	'I ap-peach-ate you.',
	"I know it's corny but you're a-maize-ing.",
	"I don't feel like forking. Wanna spoon instead?",
	'You are brew-tiful.',
	"You're super!",
	'Get jalapeño business.',
	'A cereal killer.',
	'A Blue cheese.',
	'How are you peeling?',
	'Because they cantaloupe.',
	'Raisin the roof.',
	'Romaine calm.',
	"You're kiwing me.",
	'In pizza we crust.',
	"One of my kitchen utensils seems to be playing classical music. I think it's the Chopin board.",
	'That was a whisk I was willing to take.',
	'I have a device in my kitchen which makes smoothies that make me think heaven is a place on earth. Blender Carlisle.',
	'I fell asleep beside the kitchen sink. I feel completely drained now.',
	"I would put my slices of meat on the fridge's top shelf, but the steaks were too high.",
	'A friend of mine used to install kitchen work surfaces, but they arrested him for counter fitting.',
	'I had to give up on my plan to set up a business making work surfaces for kitchens. It was counterproductive.',
	"What's cooking?",
	'Bake in my day, things were much different.',
	'I would like to live a day in the knife of you.',
];
export default puns;
