name: Vitest Unit Tests
 
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"
 
    - name: Install dependencies
      run: npm install
 
    - name: Run tests
     
      run: npm run test